### ISSUE TITLE
Add quick connection test tool

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-tool_opencast#13]
Currently, the Opencast API configuration has to be done blindly on /admin/settings.php?section=tool_opencast. If the settings aren't entered fully correctly (see #11 at least for an enhancement to add better descriptions and validation), you won't see that the connection is broken until you try to upload a video with block_opencast or try to download or try to fetch a video with repository_opencast.

I would propose to add a quick connection test tool to  /admin/settings.php?section=tool_opencast to answer the questions:
* Is there an Opencast instance running on the configured URL?
* Can Moodle connect to Opencast with the configured credentials?

Referencing https://tracker.moodle.org/browse/MDL-65053 as this might help (at least if it's implemented before this issue here is tackled)

**Comment by ferishili** [comment]
Hi @TamaraGunkel, I am going to work on this issue, could you please assign it to me. Thanks in advance.
