### ISSUE TITLE
Add help text for server url that protocol is required

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-tool_opencast#15]
If the opencast server runs on https, this has to be stated in the server url as well. Otherwise, there might be a strange behaviour through automatic redirect, which might lose the http method.
See: https://groups.google.com/a/opencast.org/forum/?fromgroups=#!topic/users/e3K0VduVEcE for details

**Comment by abias** [comment]
This issue at least has a connection to #11 or might even be resolved by #11 completely.
