### ISSUE TITLE
no support for Moodle 3.5 ?

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-tool_opencast#27]
`tool_opencast` provides API functions as well as general settings for the different opencast tools such as `block_opencast`.

Although the `block_opencast` plugin is offered for Moodle 3.5, the `tool_opencast` dependency (v3.9-r1) does not support Moodle 3.5 anymore. This prevents us from updating  `block_opencast` plugin on a Moodle v3.5.x setup.

Is there any reason why new version v3.9-r1 does not support Moodle 3.5? Moodle offers still security updates for v3.5 until 10. May 2021.

Is there a solution for this issue?

**Comment by TamaraGunkel** [comment]
Hey,
I'm sorry you didn't received a timely response. However as Moodle 3.5 is now officially EOL, we won't add support for it anymore.
