### ISSUE TITLE
Master doesn't work with block_opencast master

### ISSUE THREAD

**Issue by univietw** [Opencast-Moodle/moodle-tool_opencast#33]
It seems you forgot to push the recent master because if I check out the master of tool_opencast and block_opencast I get an error, that a newer version of tool_opencast must be installed.
Changing it to the newest tag (v3.11-r2) helps, so you only have to push the newest tag changes the master branch

**Comment by TamaraGunkel** [comment]
And I know that its currently a bit messed up (sorry for that) but use the MOODLE_311_STABLE branch if you want to have a valid dependency for the block.
