### ISSUE TITLE
Don't place specialized functions in lib.php

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-tool_opencast#36]
Today, I had a look at the diff between the latest published version of this plugin and the current master version (https://github.com/Opencast-Moodle/moodle-tool_opencast/compare/b74064ed6134746a9cba67a8560e2fda332ac3d1..fc18d396f108a979e27302f91d2e3e72297c41e7) and I spotted by chance that you have added a lib.php with specialized functions for the connection test tool.

I think you should move these functions to a dedicated class file or at least to a locallib.php file which is only required when needed. Please see https://docs.moodle.org/dev/lib.php#Other_functions for details.

**Comment by TamaraGunkel** [comment]
Hey, 
thanks for pointing this out.
I wasn't aware that the lib.php should only contain the API function. 
However, it was added when merging a PR and I will pay more attention to that in the future.
I already removed the functions in 553a9bba0c345ae97793ba8702b1c766cdab43f6.
