### ISSUE TITLE
Add a thirdpartylibs.xml file for Tabulator library

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-tool_opencast#37]
Today, I had a look at the diff between the latest published version of this plugin and the current master version (https://github.com/Opencast-Moodle/moodle-tool_opencast/compare/b74064ed6134746a9cba67a8560e2fda332ac3d1..fc18d396f108a979e27302f91d2e3e72297c41e7) and I spotted by chance that you have added the 'Tabulator' library to the plugin.

I think you should add a thirdpartylibs.xml file and reference the library there. Please see https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml for details.

**Comment by TamaraGunkel** [comment]
Thanks, also relevant for https://github.com/Opencast-Moodle/moodle-block_opencast.
