### ISSUE TITLE
Ingest uploads not working in PHP 7.4

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-tool_opencast#44]
## Problem

When using the ingest API (admin setting "ingestupload") to upload videos with PHP < 8 the uploads fail with:

> ... series exists
> ... media package created
> ... failed to add episode metadata

## Analysis

With PHP < 8 the helper class `PolyfillCURLStringFile` is used to encode xml files being sent. That class encodes the entire XML file content as a base64 string in the filename property of its base class `CURLFile`:

https://github.com/Opencast-Moodle/moodle-tool_opencast/blob/fe2d5d7107aac4884022d61e83e6c4b441b87152/classes/local/PolyfillCURLStringFile.php#L44-L47

The `PolyfillCURLStringFile` (among other params) then gets passed to `curl_setopt` as `CURLOPT_POSTFIELDS`. After `curl_exec` we see the error:

> couldn't open file "data://application/octet-stream;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPGR1YmxpbmNvcmUgeG1sbnM9Imh0dHA6Ly93d3cub3BlbmNhc3Rwcm9qZWN0Lm9yZy94c2QvMS4wL2R1YmxpbmNvcmUvIiB4bWxuczpkY3Rlcm1zPSJodHRwOi8vcHVybC5vcmcvZGMvdGVy

Decoded:

```xml
<?xml version="1.0" encoding="utf-8"?>
<dublincore xmlns="http://www.opencastproject.org/xsd/1.0/dublincore/" xmlns:dcterms="http://purl.org/dc/ter
```

Somewhere either in `curl_setopt` or `curl_execute` the base64 encoded xml gets truncated to 235 characters.

## Environment

* Moodle 3.11.5
* PHP 7.4.28
* OS: CentOS 7

**Comment by TamaraGunkel** [comment]
Hey,
I tried to reproduce the error but not successfully.
The ingest upload with PHP 7.4 works in my setup (moodle-php-apache docker container).
Are you sure that this is an issue with the Moodle Plugin? Did you try another PHP version?

**Comment by t-schroeder** [comment]
Hey, I've debugged it and saw it go to [this line](https://github.com/curl/curl/blob/curl-7_29_0/lib/formdata.c#L1268) in libcurl. CentOS 7 comes with libcurl version 7.29 which apparently doesn't support the way this plugin encodes the file data in the CURLFile's `$filename`. See: https://github.com/Opencast-Moodle/moodle-tool_opencast/blob/74613b52601639dcc526d9e3b1e8cd090dfb5b55/classes/local/PolyfillCURLStringFile.php#L44-L47

 I guess, to fix this we'd need to use a newer version of libcurl which in our case means switching to a different OS.

**Comment by ferishili** [comment]
This issue is fix by opencast php library integration in https://github.com/Opencast-Moodle/moodle-block_opencast/commit/f1e8538e44035110d16379dc66ce5636227e6aa4
