### ISSUE TITLE
Fix default instance change

### ISSUE THREAD

**Issue by TamaraGunkel** [Opencast-Moodle/moodle-tool_opencast#46]
Currently, the default instance is directly connected with the settings without instanceid such as `apiurl`. If the default instance is switched to another instance, this results in an association of the settings with the wrong instance. Changing the default instance should not have any effect on the settings itself.

**Comment by ferishili** [comment]
Fixed and merged via 91b6fc9e3103a9235bdbbd5461d1a37de869756a
