### ISSUE TITLE
Refactor settings

### ISSUE THREAD

**Issue by TamaraGunkel** [Opencast-Moodle/moodle-tool_opencast#47]
To ensure backwards compatibility with older block versions, the tool still uses the old settings like `apiurl`without the instanceid (`apiurl_1`). We should drop this behaviour in favor of more clean and reliable code. A good way to do that, would be to change this with the first release for Moodle 4 because all universities will probably upgrade the all plugins.

**Comment by ferishili** [comment]
FIxed and merged via 91b6fc9e3103a9235bdbbd5461d1a37de869756a
