### ISSUE TITLE
[codechecker error] Unexpected MOODLE_INTERNAL check. 

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-tool_opencast#59]
Hello @NinaHerrmann,
testing the actual branch update/4.3 the moodle codechecker is not happy with the following:

```
admin/tool/opencast/classes/local/environment_util.php
    #19: defined('MOODLE_INTERNAL')·||·die;
    Unexpected MOODLE_INTERNAL check. No side effects or multiple artifacts detected. (moodle.Files.MoodleInternal.MoodleInternalNotNeeded)

```
Please, can you have a look at it?

**Comment by NinaHerrmann** [comment]
I am closing this issue - as the warning basically just says you are doing a double moodle internal check.
